[package]
name = "node-to-rust"
version = "0.1.0"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Livio Ribeiro <livioribeiro@outlook.com>"
]

[lib]
name = "ffi_example"
crate-type = ["dylib"]

[dependencies]
libc = "*"
