[package]
name = "perl-to-rust"
version = "0.1.0"
#modified based on python version
authors = [
  "Hao Wu <echowuhao@gmail.com>",
  "Livio Ribeiro <livioribeiro@outlook.com>"
]

[lib]
name = "ffi_example"
crate-type = ["dylib"]

[dependencies]
libc = "*"
